go-pay/gopay

- body_map.go
- wechat_params.go
> change generateXml

- .gitignore
- .vscode/settings.json
- README.md
- body_map.go
- wechat/client.go
- wechat/model.go
* 请求单次分账（正式）：client.ProfitSharing() 
* 请求多次分账（正式）：client.MultiProfitSharing()
* 查询分账结果（正式）：client.ProfitSharingQuery()
* 添加分账接收方（正式）：client.ProfitSharingAddReceiver()
* 删除分账接收方（正式）：client.ProfitSharingRemoveReceiver()
* 完结分账（正式）：client.ProfitSharingFinish()
* 分账回退（正式）：client.ProfitSharingReturn()
* 分账回退结果查询（正式）：client.ProfitSharingReturnQuery()
> 增加微信普通商户版分账接口

- wechat/service_api.go
与微信公众号获取用户基本信息的请求路径不同，用于微信开放平台的微信登陆流程
> 获取用户基本信息(UnionID机制)(微信开放平台)

- .gitignore
- alipay/client_test.go
- alipay/service_api.go
https://github.com/iGoogle-ink/gopay/issues/6
支付宝部分支持
> 支持多方式传入支付宝证书

- wechat/v3/client.go
- wechat/v3/client_test.go
> 微信 apiv3 init

- go.mod
- wechat/client.go
- wechat/merchant.go
- wechat/param.go
> 添加微信证书方法支持传证书内容

- wechat/v3/cert.go
> 修复获取微信平台证书响应Code值错误

- README.md
- alipay/client_test.go
- alipay/funds_api.go
- alipay/model.go
> 添加查询转账订单API

- README.md
- alipay/funds_api.go
- alipay/model.go
增加两个接口
+ 线上资金授权冻结接口
+ 资金授权解冻接口
> 增加资金授权解冻 API

- README.md
- alipay/funds_api.go
- alipay/model.go
> 增加资金授权操作查询 API

- alipay/model.go
如图中所示，因在官方文档并未找到以下两个参数。故此删除
+ DeductBillInfo
+ TransferBillInfo
请检查支付宝接口官方文档
https://opendocs.alipay.com/apis/api_28/alipay.fund.trans.common.query
局部截图
> 删除单据查询多余参数

- README.md
- alipay/funds_api.go
- alipay/model.go
增加一个支付宝资金类接口
+ 批量转账明细查询
支付宝资金分类下接口已完成
> 增加批量转账明细查询 API

- alipay/client.go
- alipay/funds_api.go
- alipay/funds_api_test.go
- alipay/payment_api.go
- examples/main.go
1.增加一个获取签名的方法
2.修改alipay.fund.auth.order.freeze(资金授权冻结接口)不需要发起接口请求
> 1.增加一个获取签名的方法 2.修改alipay.fund.auth.order.freeze(资金授权冻结接口)不需要发起接口请求

- .gitignore
- README.md
- wechat/v3/client_test.go
- wechat/v3/constant.go
- wechat/v3/merchant.go
- wechat/v3/model.go
新增wechat v3 资金应用-分账模块中的部分接口，实现的接口列表已经标注在readme里面；
调整了下client_test.go中的配置信息，改成了读取一个conf.json【已经配置在ignore文件中】
> feat 新增wechat 分账模块接口

- pkg/xlog/log.go
Provide set func for logger, then we can replace with custom logger
> public logger and provide set func

- pkg/xlog/color.go
- pkg/xlog/debug_logger.go
- pkg/xlog/error_logger.go
- pkg/xlog/info_logger.go
- pkg/xlog/log.go
- pkg/xlog/warn_logger.go
- wechat/v3/encrypt_decrypt.go
- wechat/v3/notify.go
- wechat/v3/sign.go
- wechat/v3/sign_test.go
- log接口方法公有化
- v3加密兼容性问题
- v3动账回调解密
- v3 jsapi返回参数签名使用先前请求sign的ts和nonce（按说其他相关接口也应该需要调整）
> feat: 加解密补充更新

- body_map.go
- constant.go
- doc/wechat_v3.md
- go.mod
- go.sum
- qq/client.go
- qq/param.go
- qq/payment_api.go
- release_note.txt
- wechat/client.go
- wechat/merchant.go
- wechat/param.go
- wechat/payment_api.go
- wechat/red.go
- wechat/sign.go
- wechat/v3/applyment_for_sub.go
- wechat/v3/constant.go
- wechat/v3/model.go
- wechat/v3/pay_combine.go
- wechat/v3/pay_partner.go
(1) 微信V3：新增 client.V3EcommerceApply()，二级商户进件
(2) 微信V3：新增 client.V3EcommerceApplyStatus()，查询申请状态
(3) 微信V3：公有化 wechat.GetReleaseSign()、wechat.GetSandBoxSign() 方法
> Add new api

- apple/model.go
> pending_renewal_info 修复为数组

- qq/oplatform_api.go
> Update AccessToken ExpiresIn

- apple/notification_v2.go
- apple/notification_v2_model.go
- apple/notification_v2_test.go
- doc/apple.md
- go.mod
- go.sum
苹果支付服务端通知v2 版本实现
https://developer.apple.com/documentation/appstoreservernotifications
> feat: apple pay notification v2

- wechat/v3/model.go
微信分账接收方结构体修改;添加"分账明细单号(detail_id)"字段
文件: wechat/v3/models.go:line:1593
微信文档:
商户文档：https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter8_1_1.shtml
服务商文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_1.shtml
> 微信分账接收方结构体修改;添加"分账明细单号(detail_id)"字段

- doc/paypal.md
- paypal/constant.go
- paypal/model.go
- paypal/subscriptions.go
- paypal/subscriptions_test.go
> feat: paypal add Interface of createBillingPlan

- qq/oplatform_api.go
callback(
{
　　"error":100016,
　　"error_description":"access token check failed",
}
);
用户凭据过期和未申请unionID接口调用权限都会返回错误信息
> 增加获取openid失败的错误信息

- alipay/model.go
FundAuthOperationDetailQuery 增加 order_status字段
辛苦合并一下，我们急着用感谢
> FundAuthOperationDetailQuery add order_status fields

- alipay/goods_api.go
原来的那个没有素材上传的接口，把素材上传接口加了一个，其它的素材上传接口暂时未兼容，不过也可以拿这个来修改，已经测试可用
> 添加支付宝素材上传的接口

- examples/wechat/wx_RefundV3.go
> 1、新增微信支付退款v3版本的demo

- alipay/model_merchant.go
分账查询结果，详见 https://opendocs.alipay.com/open/02o6e0?pathHash=158daac5
> feat: RoyaltyDetail 对象增加 detail_id 字段

- alipay/model_payment.go
> fix: TradeSettleDetailList is array

- apple/notification_v2_model.go
续订信息缺失`renewalDate` 属性, 续订到期时间, 官网有此属性. 使用中发现没有, 望补充....
> renewalDate: append RenewalInfo attribute

- alipay/model_member.go
> Update model_member.go 增加实名信息字段

- apple/unsign_jwt.go
1.修复苹果交易签名信息未验证bug
2.减少不必要的header反序列化
> bugfix：修复苹果交易签名信息未验证bug

- alipay/model_payment.go
- paypal/model.go
https://opendocs.alipay.com/open/02fkaw
增加缺少的 trade_unsettled_amount 字段
> add TradeUnsettledAmount of TradeSettleInfo

- apple/consumption.go
> fix：SendConsumptionInformation AppPay 成功状态判断错误

- alipay/client.go
- alipay/client_test.go
> feat: alipay client expose http client for customization

- apple/notification_v2_model.go
https://developer.apple.com/documentation/appstoreservernotifications/notificationtype
> 苹果支付增加一次性购买通知类型常量
