go-pay/gopay

alipay/client.go
支付宝手机wap支付接口的quit_url是可选参数，简易去掉必填的错误检查逻辑
=> remove error check for option quit_url

alipay/model.go, go.mod
ExpiresIn和ReExpiresIn 支付宝返回的不是字符串，是正常时间戳
=> 修复支付宝oauthTokenInfo返回的json是int类型

alipay/client.go
使用公钥证书的方式，获取accessToken时验签错误修复
=> 使用公钥证书时，签名需要传递公钥证书、支付宝根证书

body_map.go, body_map_test.go, go.mod
support using higher order func to set BodyMap Value
```go
var b = make(BodyMap)
b.Set("test",func(b BodyMap){
b.Set("sub", func(b BodyMap) {
b.Set("sub-sub","value")
})
})
```
which is equal 
```
{
"test":{
"sub":{
"sub-sub":"value",
},
},
}
```
=> feat: support higher order func to set mapBody

go.mod, go.sum, wechat/client.go, wechat/param.go
1. 根据 [微信证书使用文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_3)，支持微信pem证书与p12证书二选一。P12 证书则是转成 PEM，[官方示例代码](https://github.com/golang/crypto/blob/master/pkcs12/pkcs12_test.go#L34)
2. 删除无用字段和新增两个添加证书内容的方法
已经通过 refund 方法自测过了，能正常退款。
=> 支持微信pem证书与p12证书二选一

README.md, alipay/client.go, alipay/client_test.go, alipay/common_api.go, alipay/payment_api.go, alipay/sign.go, alipay/util_api.go, alipay/zhima_api.go, body_map.go, constant.go, examples/alipay/alipay_TradeOrderSettle.go, examples/wechat/wx_ServiceApi.go, pkg/util/string.go, pkg/xhttp/client.go, pkg/xhttp/model.go, qq/client.go, qq/payment_api.go, release_note.txt, wechat/base_api.go, wechat/client.go, wechat/merchant.go, wechat/payment_api.go, wechat/red.go, wechat/v3/pay_public_api.go
版本号：Release 1.5.29
发布时间：2021/02/23 21:32
修改记录：
(1) 支付宝：重构 client.PostAliPayAPISelf()，具体参考 client_test.go 内的 TestClient_PostAliPayAPISelf() 方法
(2) BodyMap：新增 bm.SetFormFile() 的部分方法，修改 bm.Get() 方法，新增bm.GetString() 方法
(3) xHttp：更新 httpClient， httpClient.Type() 支持 TypeMultipartFormData 类型
=> 重构支付宝client的 PostAliPayAPISelf() 方法，使其更加灵活

README.md, alipay/funds_api.go, alipay/model.go
增加两个支付宝资金类接口
+ 资金授权冻结接口: client.FundAuthOrderFreeze()
+ 资金授权发码接口: client.FundAuthOrderVoucherCreate()
=>  增加资金授权冻结接/发码 API

README.md, alipay/funds_api.go, alipay/model.go
增加三个支付宝资金类接口
+ 资金授权撤销
+ 批次下单
+ 批量转账关单
=> 增加资金授权撤销 API

README.md, alipay/model.go, alipay/payment_api.go, alipay/payment_api_test.go, alipay/zhima_api.go, alipay/zhima_api_test.go, examples/alipay/alipay_ZhimaCreditEpSceneRatingInitialize.go
1. 支付宝API-->聚合支付订单咨询服务`client.TradeOrderAggregateConsult()` --写完才发现已弃用 。。。。
2. README_update
3. 单元测试新增; 订单资讯服务单元测试+芝麻企业信用信用评估初始化
4. 新增API: alipay-芝麻企业信用信用评估初始化`ZhimaCreditEpSceneRatingInitialize`
=> alipay_add_api

pkg/xhttp/client.go
希望 添加 对 Proxy支持  和  暴露 对 Transport的设置  ( Proxy支持 参考: http.DefaultTransport)
```golang
// NewClient , default tls.Config{InsecureSkipVerify: true}
func NewClient() (client *Client) {
client = &Client{
HttpClient: &http.Client{
Timeout: 60 * time.Second,
Transport: &http.Transport{
TLSClientConfig:   &tls.Config{InsecureSkipVerify: true},
DisableKeepAlives: true,
Proxy: http.ProxyFromEnvironment,  
},
},
Transport:     nil,
Header:        make(http.Header),
requestType:   TypeUrlencoded,
unmarshalType: string(TypeJSON),
Errors:        make([]error, 0),
}
return client
}
func (c *Client) SetTransport(transport *http.Transport) (client *Client) {
c.Transport = transport
return c
}
```
考虑到支付处理服务 可能处在 网络受限 状态下
=> goproxy support and expose transport settings

wechat/v3/client_test.go, wechat/v3/constant.go, wechat/v3/model.go, wechat/v3/profit_share.go
新增 微信v3申请分账账单
修改 微信v3解冻剩余资金传参方式为BodyMap，支持服务商模式
修改 微信v3分账接口，Rsp新增sub_mchid字段，兼容服务商模式。
=> 新增微信V3申请分账账单，更新微信V3解冻剩余资金传参方式，更新部分Rsp兼容服务商模式

alipay/client.go
app_auth_token上方取出后并未加到pubBody中
=> 解决第三方授权令牌没有加入到提交数据中的问题

body_map.go
=> 拼接参数时做encode

alipay/sign.go, alipay/sign_test.go, body_map.go, examples/alipay/alipay_TradeOrderSettle.go, pkg/xhttp/client.go, pkg/xhttp/client_test.go, qq/param.go, wechat/param.go, wechat/v3/cert.go
在如下的追踪链中, 丢失了请求微信的过程.
部分用户可能需要替换Http客户端为自己实现的客户端, 方便添加 Hook 或者其他操作.
我的想法是添加 `HttpDoer` 接口 和 全局的 `DefaultHttpClient` 实现的.
请大佬指点.
```
type mockDoer struct {
doer *http.Client
}
func (c mockDoer)Do(req *http.Request) (*http.Response, error) {
// 记录日志等...
// log(req)
res,err := c.doer.Do(req)
// log(res)
return res, err
}
```
因为使用的是全局的 DefaultHttpClient.
gopay里已经在使用的 xhttp.NewClient 是不用修改的, 使用者直接替换这个默认值, 就可以调用自己封装的`Do`方法
```
doer := &mockDoer{doer: &http.Client{ Timeout: 10*time.Second }}
xhttp.DefaultHttpClient = doer
```
如果有用户使用了gopay的 xhttp 包, 但是不想使用 `xhttp.DefaultHttpClient`, 那么也可以选择用 `WithHttpDoer` 方法替换
```
doer := &mockDoer{doer: &http.Client{ Timeout: 10*time.Second }}
client := xhttp.NewClient(xhttp.WithHttpDoer(doer))
```
=> 支持替换 xhttp.Client 中的 HttpClient 为用户自定义实现了 HttpDoer 接口的客户端

alipay/error.go, alipay/error_test.go, alipay/model.go, alipay/payment_api.go, alipay/payment_api_test.go
**这个PR 包含了举例用途的代码修改  还不能合并**
将现有的ErrorResponse 从model.go 移动到了error.go(新增), 出于将要为其添加方法的考虑, 认为他不再只是一个model, 所以移出来了.
然后ErrorResponse 实现了error 的接口, 可以被当作error 返回
相关issues: #221
=> Error response enhancement

pkg/xlog/log.go
Don't know why remove xlog public setter [v1.5.74](https://github.com/go-pay/gopay/commit/f1c47485f9fe8e8f3ccd8ca5819f2c797aaffd7f), I need it to set with custom logger for redirecting log output
=> feat: custom xlog to redirect log

alipay/client.go, alipay/member_api.go, alipay/member_api_test.go, doc/alipay.md
1. 添加`PageExecute`用以只生成签名, 不发送请求. 和官方`SDK`命名一致
2. 添加`UserAgreementPageSignInApp`放在, 在`App`签约唤醒支付宝使用
=> add: 添加 app 签约接口

alipay/model.go
Add: 支付宝资金账户资产查询接口返回当前支付宝账户的实时冻结余额：freeze_amount 
https://opendocs.alipay.com/open/02byuq?scene=c76aa8f1c54e4b8b8ffecfafc4d3c31c
=> 添加支付宝资金账户资产查询接口返回参数：freeze_amount

qq/oplatform_api.go
报错信息
`qq qqAuth.GetOpenId error [unmarshal error]: invalid character ')' after top-level value, bytes:  {"client_id":"101221111","openid":"9A12284F472F721xxx13E0307","unionid":"UID_C5444xxxxx4E9DBFxxx9DDC9"} );`
bs = bytes.TrimLeft(bs, "callback(")
bs = bytes.TrimRight(bs, ");") // mac 这句没问题，但是linux中就会报上面的错
=> fix bug: [unmarshal error]: invalid character ')' after top-level value,

alipay/merchant_api.go, alipay/model_merchant.go
统一收单确认结算接口 是  [alipay.trade.order.settle](https://opendocs.alipay.com/open/028xqz)（统一收单交易结算接口）的必要前置接口。
=> feat: 增加 alipay.trade.settle.confirm(统一收单确认结算接口)

wechat/v3/media.go, wechat/v3/model_complaint.go
1.新增投诉信息中的图片下载查询接口；
2.修复投诉历史详情查询接口数据结构问题，媒体资源应该是一个数组类型；
上述问题已在项目调试过程中经过测试，没啥大问题OK，大佬可以帮忙看看。
=> 微信支付消费者投诉新增对接接口

apple/client.go
=> fix[apple]: NewClient set isProd

alipay/model_payment.go
TradeQuery添加buyer_open_id。
以OpenID形式接入Alipay，将使用buyer_open_id字段。
userid模式将弃用。
=> feat: 添加buyer_open_id

apple/notification_v2.go
根据苹果文档要求，第一次调用不能传递paginationToken参数，所以做了处理。
=> fix(apple): fix apple GetNotificationHistory api imp

apple/notification_v2_model.go
根据官方最新文档说明，更新了通知版本NotificationVersion字段
由原来结构体
NotificationV2Payload.NotificationVersion   `json:notificationVersion`
调整为
NotificationV2Payload.Version    `json:version`
=> 根据官方最新文档说明调整字段Version Update notification_v2_model.go

paypal/client.go
上线后一段时间经常出现：errcode: 401, errmsg: {401 {"error":"invalid_token","error_description":"Access Token not found in cache"} 0x4007130d80 0x40001c37c0}
发现token从初始化client后 一直没做刷新，于是在 初始化client 时，开个协程，定期更新token
=> paypal 在到期结束前的一半时间内，自动刷新token

alipay/request.go
Sorry，上次提交的时候文件上传&验签确实成功了，但是参数没有解析，又找了好久的文档，发现真实情况是：
本接口为文件上传类接口，与普通OpenAPI接口的入参构造格式不同，如果您没有使用官方SDK发起OpenAPI调用，自行构造HTTP请求时需注意以下事项：
1. 本接口使用multipart/form-data内容格式上传文本参数与文件，文件字段需传入filename文件名，并带扩展名（例如：Content-Disposition: form-data; name="file_content"; filename="example.png"），否则会提示图片类型为空。
2. 对于v2版本的协议，**本接口的业务请求参数没有封装在biz_content字段中，直接平铺到请求的body中**。
也就是说，对于业务参数不需要放到biz_content，也不需要加密处理，所以移除了参数加密的代码，详见这个文档：
https://opendocs.alipay.com/mini/510d4a72_alipay.merchant.item.file.upload
=> [Fix file upload method]: remove file upload biz content encrypt params

paypal/access_token.go, paypal/client.go, paypal/request.go
1. paypal.Client 新增方法 `SetProxyUrl` 来指定 paypal 代理 URL，用作大陆地区加速请求
=> feat: specify proxy url for paypal client

paypal/client.go
paypal 在 NewClient 中执行了获取 AccessToken 的操作，如果想要使用代理 Url，需要在请求前指定好代理地址。为了不造成破坏性改动，最终采用了 Functional Options Pattern 来设置代理 Url。
=> feat: paypal client with proxy url option

apple/transaction_model.go
fix bug:  apple refunded transaction  revocationReason type should be  int32
https://developer.apple.com/documentation/appstoreserverapi/revocationreason
=> Update  Apple Refunded Transaction  revocationReason

alipay/client.go, allinpay/client.go, wechat/client.go, wechat/v3/client.go
为wechat.ClientV3 新增了一个构造方法，支持自定义xhttp.Client。
=> feat: 为client 增加 set httpClient 公有方法

paypal/client.go, paypal/model.go, paypal/order_test.go
1. 丰富 paypal order 的授权接口返回值: 以便获取 AuthorizationId 进行后续操作
2. 相关 Issue https://github.com/go-pay/gopay/issues/402
=> fix(paypal): fulfill paypal order authorize response model

wechat/v3/notify.go
=> 增加服务商子商户处置记录回调解密

paypal/client.go
由于NewClient时就会执行GetAccessToken函数，在阿里云国内服务器下会连接失败，想要使用http代理就需要在NewClient时指定HttpClient option。
=> feat: paypal client with http client option

paypal/constant.go, paypal/model.go, paypal/webhook.go, paypal/webhook_test.go
增加五个webhook相关的接口
- createWebhook
- listWebhook
- showWebhookDetail
- updateWebhook
- deleteWebhook
- verifyWebhookSignature (在沙盒模式下失败，正式环境不知道，反正我沙盒失败了)
- showWebhookEventDetail
=> feat(paypal): add webhook support

paypal/client.go, paypal/client_test.go, paypal/constant.go, paypal/model.go, paypal/payment_token.go, paypal/payment_token_test.go, paypal/payout.go
1.新增payment method token API
2.paypal增加自动刷新Token选项,用以支持client每次调用都需要重新生成的场景。解决该场景下开启自动刷新token协程可能出现的内存泄漏问题以及错误
3.paypal client代码修正Struct Client has methods on both value and pointer receivers警告
=> Feat/paypal 新增payment method token API

apple/refund.go
兼容revision为空的情况，否则接口会出现{"errorCode":"4000005","errorMessage":"Invalid request revision."}
=> fix: 苹果退款历史查询

paypal/constant.go, paypal/model.go, paypal/products.go, paypal/products_test.go, paypal/subscriptions.go, paypal/subscriptions_test.go
增加paypal接口 并增加测试用例 
产品功能接口 创建、更新、详情、列表接口
订阅计划接口 订阅计划列表、订阅计划详情、更新订阅计划  
订阅接口 订阅生成链接 、 取消订阅、暂停订阅、激活订阅、 订阅事务列表
=> 增加paypal的产品、计划、订阅 接口
